spring.profiles.active=dev
#mybatis-plus
#mybatis-plus.mapper-locations=classpath:mappers/*.xml
mybatis-plus.type-aliases-package=cn.njcit.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true 
mybatis-plus.configuration.aggressive-lazy-loading=false
mybatis-plus.configuration.lazy-loading-enabled=true

pagehelper.helper-dialect=mysql
pagehelper.reasonable=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
logging.level.org.springframework.web=debug
logging.level.cn.njcit=DEBUG
security.auth-protected-patterns=/studentManage/*,/classManage/*,/courseMan/*,/courseManage/*,/attendance/*,/attendClassSetting/*,/userLoginRecord/*,/userManage/*,/roleManage/*,/menuManage/*
 